name: CryptoLib

on: 
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  #
  # Minimal Build
  #
  minimal_build:
    # Container Setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install -y lcov libcurl4-openssl-dev libmariadb-dev libmariadb-dev-compat python3 
    - name: Install Python Libraries
      run: sudo pip install pycryptodome
    - name: Install Libgcrypt
      run: >
        bash ${GITHUB_WORKSPACE}/support/scripts/update_env.sh
    # End Container Setup
    
    - name: Minimal Build Script
      working-directory: ${{github.workspace}}
      run: bash ${GITHUB_WORKSPACE}/support/scripts/build_minimal.sh

  #
  # Internal Build
  #
  internal_build:
    # Container Setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install -y lcov libcurl4-openssl-dev libmariadb-dev libmariadb-dev-compat python3
    - name: Install Python Libraries
      run: sudo pip install pycryptodome
    - name: Install Libgcrypt
      run: >
        ansible-playbook ${GITHUB_WORKSPACE}/support/scripts/codeql.yml
    # End Container Setup
    
    - name: Internal Build Script
      working-directory: ${{github.workspace}}
      run: bash ${GITHUB_WORKSPACE}/support/scripts/build_internal.sh

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:c-cpp"

    - name: Code-Coverage
      working-directory: ${{github.workspace}}
      run: make gcov

    - name: Upload 
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: 71699f25-12a3-44a4-8a83-be777b9e577a
      with:
        files: 'coverage/*.c.gcov'
        verbose: true

  #
  # KMC Build
  #
  # kmc_build:
  #   # Container Setup
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Update
  #     run: sudo apt-get update
  #   - name: Install Dependencies
  #     run: sudo apt-get install -y lcov libcurl4-openssl-dev libmariadb-dev libmariadb-dev-compat python3
  #   - name: Install Python Libraries
  #     run: sudo pip install pycryptodome
  #   - name: Install Libgcrypt
  #     run: >
  #       bash ${GITHUB_WORKSPACE}/support/scripts/update_env.sh
  #   # End Container Setup
    
  #   - name: KMC Build Script
  #     working-directory: ${{github.workspace}}
  #     run: bash ${GITHUB_WORKSPACE}/support/scripts/build_kmc.sh
    
  #   - name: Code-Coverage
  #     working-directory: ${{github.workspace}}
  #     run: make gcov

  #   - name: Upload 
  #     uses: codecov/codecov-action@v4
  #     env:
  #       CODECOV_TOKEN: 71699f25-12a3-44a4-8a83-be777b9e577a
  #     with:
  #       files: 'coverage/*.c.gcov'
  #       verbose: true

  #
  # Wolf Build
  #
  wolf_build:
    # Container Setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install -y lcov libcurl4-openssl-dev libmariadb-dev libmariadb-dev-compat python3 autoconf libtool
    - name: Install Python Libraries
      run: sudo pip install pycryptodome
    - name: Install Libgcrypt
      run: >
        bash ${GITHUB_WORKSPACE}/support/scripts/update_env.sh
    - name: Clone WolfSSL
      run: git clone --depth 1 --branch v5.6.0-stable https://github.com/wolfSSL/wolfssl.git /tmp/wolfssl
   
     #      cmake -DCMAKE_INSTALL_PREFIX=/home/runner/.local -DWOLFSSL_AESCCM=yes -DWOLFSSL_AESSIV=yes -DWOLFSSL_CMAC=yes ..;
    - name: Build WolfSSL
      run: mkdir /tmp/wolfssl/build;
           cd /tmp/wolfssl/build;
           cmake -DWOLFSSL_AESCCM=yes -DWOLFSSL_AESSIV=yes -DWOLFSSL_CMAC=yes ..;
           cmake --build .;
           sudo make install;
           sudo ldconfig;
    # End Container Setup
    
    - name: Wolf Build Script
      working-directory: ${{github.workspace}}
      run: bash ${GITHUB_WORKSPACE}/support/scripts/build_wolf.sh
    
    - name: Code-Coverage
      working-directory: ${{github.workspace}}
      run: make gcov

    - name: Upload 
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: 71699f25-12a3-44a4-8a83-be777b9e577a
      with:
        files: 'coverage/*.c.gcov'
        verbose: true
      
  #
  # RHEL Build
  #
  rhel_build:
    # Container Setup
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8
    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: yum update -y
    - name: Install Dependencies
      run: yum install -y epel-release python38-devel libcurl-devel git cmake gcc java-11-openjdk-devel openssl wget bzip2 ldconfig mariadb-devel mariadb-common mariadb-connector-c mariadb-connector-c-config mariadb-errmsg mariadb-gssapi-server
      # Might want to trim this down, but these dependencies should work for KMC
    - name: install lcov
      run: yum install -y --enablerepo=epel lcov
    - name: Install Python Dependencies
      run: pip3 install pycryptodome
    - name: Install Libgcrypt
      run: >
        bash ${GITHUB_WORKSPACE}/support/scripts/update_env.sh
    # End Container Setup

    - name: RHEL Build Script
      working-directory: ${{github.workspace}}
      run: source ~/.bashrc && ${GITHUB_WORKSPACE}/support/scripts/build_rhel.sh
    
    - name: Code-Coverage
      working-directory: ${{github.workspace}}
      run: source ~/.bashrc && make gcov

    - name: Upload 
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: 71699f25-12a3-44a4-8a83-be777b9e577a
      with:
        files: 'coverage/*.c.gcov'
        verbose: true
